language: python
sudo: false
addons:
  apt:
    packages:
      - python-gobject
      - python3-gobject
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install coverage coveralls -e .[test]
script:
    - coverage run -m gtimelog.tests
after_success:
    - coveralls
notifications:
    email: false
