language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install freezegun coverage coveralls -e .
script:
    - coverage run -m gtimelog.tests
after_success:
    - coveralls
notifications:
    email: false
