language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - travis_retry pip install coverage coveralls -e .
script:
    - coverage run -m gtimelog.tests
after_success:
    - coverage report
    - coveralls
notifications:
    email: false
