language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install freezegun coverage coveralls -e .
script:
    - make coverage
after_success:
    - coveralls
notifications:
    email: false
