language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install coverage coveralls .
script:
    - coverage run ./runtests
after_success:
    - coveralls
notifications:
    email: false
